#===[ Secrets ]=========================================================
#
# This file is meant for storing secret information that is never
# published or committed to a revision control system.
#
#---[ Values ]----------------------------------------------------------

# Email address of administrator that will get requests for assistance from users:
administrator_email: 'joe@runway.is'

# Secret key for getting an ATOM feed of private comments:
comments_secret: df1df540f7a27eeaf809fd8c09a49792c42829a6436cb6b2b25a79429256933d940c83a795401ff1a7cb6dc1acd883aa69f38bc65afd7c04f31161f6a7a0fbe9

# The Rails secret_key_base
# Used by config/initializers/secret_token.rb
secret_key_base: e9459cf245092f6b08fde36fd80177aa968f8c95d932d8acc8641ed38a0d53eec45592d8f4148495687a55b28afd6b32920cb68119d47ee02f2f4649d40a6798

#===[ fin ]=============================================================
